<a href="https://colab.research.google.com/github/gitbyjay25/Phase25/blob/main/Numpy3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Array Operation in Numpy

### Arithmaric Operation  : ⚠️ Must be same shape for element-wise ops.

In [46]:
import numpy as np

In [ ]:
a=np.array([1,4,5,8,0])
b=np.array([2,7,4,1,6])

In [ ]:
a+b

array([ 3, 11,  9,  9,  6])

In [ ]:
a-b

array([-1, -3,  1,  7, -6])

In [ ]:
a*b

array([ 2, 28, 20,  8,  0])

In [ ]:
a/b

array([0.5       , 0.57142857, 1.25      , 8.        , 0.        ])

### Comparision Operations : Returns a boolean array

In [ ]:
print(a>=b)

[False False  True  True False]


In [ ]:
a==b

array([False, False, False, False, False])

### 🔶 np.where(condition, value_if_true, value_if_false)


In [ ]:
a

array([[3, 5, 2],
       [3, 2, 5]])

In [ ]:
result=np.where(a>3,1,0)
result

array([[0, 1, 0],
       [0, 0, 1]])

### Matrix Operations
Matrix operations are different from element-wise ops.

In [ ]:
a=np.random.randint(2,8,(2,3))
a


array([[3, 5, 2],
       [3, 2, 5]])

In [ ]:
np.shape(a)

(2, 3)

In [ ]:
b=np.random.randint(4,12,(3,4))
b

array([[ 4,  8,  8,  6],
       [ 9,  6,  7, 10],
       [ 8, 11,  7, 10]])

In [ ]:
np.shape(b)

(3, 4)

In [ ]:
a@b

array([[73, 76, 73, 88],
       [70, 91, 73, 88]])

In [ ]:
(a.dot(b))

array([[73, 76, 73, 88],
       [70, 91, 73, 88]])

### Aggregate Functions

In [ ]:
a.sum()

np.int64(20)

In [ ]:
b.sum()

np.int64(94)

In [ ]:
b.mean()

np.float64(7.833333333333333)

In [ ]:
a.max()

np.int64(5)

In [ ]:
b.min()

np.int64(4)

In [ ]:
b.std()

np.float64(1.9075871903765995)

In [ ]:
print(a.sum(axis=0))  # Column-wise: [6 7 7]
print(a.sum(axis=1))  # Row-wise: [10 10]


[6 7 7]
[10 10]
