<a href="https://colab.research.google.com/github/gitbyjay25/Phase25/blob/main/Numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# ***Indexing and slicing ***

In [1]:
import numpy as np

### **Slicing 1D**

In [5]:
a=np.array([1,2,3,4,5,6,7,8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [8]:
a[1]

np.int64(2)

In [10]:
a[4]

np.int64(5)

In [13]:
a[1:7:2]

array([2, 4, 6])

### Slicing 2D

In [14]:
a=np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
a[1,3]

np.int64(8)

In [18]:
a[1]

array([5, 6, 7, 8])

In [25]:
a[:,2]

array([3, 7])

In [27]:
a[0:2,1:2]

array([[2],
       [6]])

### Boolean Indexing

In [28]:
mask=a>3
print(mask)

[[False False False  True]
 [ True  True  True  True]]


In [29]:
print(a[mask])

[4 5 6 7 8]


In [32]:
print(a[:,3])

[4 8]


In [33]:
print(a[::-1])

[[5 6 7 8]
 [1 2 3 4]]


In [39]:
print(a[1,::-1])

[8 7 6 5]
