<a href="https://colab.research.google.com/github/gitbyjay25/Phase25/blob/main/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy

In [36]:
import numpy as np

### Creaing Numpy Arrays

*  From a List
* 2D Array  
* np.zeros()	All elements zero
* np.ones()	All elements one
* np.empty()	Random garbage values
* np.arange()	Range of numbers
* np.linspace()	Equal intervals between values
* np.eye()	Identity matrix
* np.full()	Custom fill value


NumPy arrays are homogeneous (all elements same datatype).

Every operation is vectorized = much faster.


In [ ]:
arr=np.array([1,2,3,4,5])

In [ ]:
arr

array([1, 2, 3, 4, 5])

In [ ]:
print(type(arr))

<class 'numpy.ndarray'>


In [ ]:
arr2D=np.array([[1,2,3],[4,5,6]])

In [ ]:
arr2D

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
type(arr2D)

numpy.ndarray

### np.zeros() - Array of Zeros

In [3]:
a=np.zeros(5)

In [4]:
a

array([0., 0., 0., 0., 0.])

In [11]:
b=np.zeros((3,4))
b

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### np.ones() _ array of ones

In [13]:
m=np.ones(8)
m

array([1., 1., 1., 1., 1., 1., 1., 1.])

In [15]:
n=np.ones((2,4))
n

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### np.empty() - Garbage value

In [16]:
s=np.empty((4,6))
s


array([[-0.25, -0.5 ,  0.  , -0.25,  0.25, -0.5 ],
       [ 0.5 , -0.25,  0.25,  0.  ,  0.5 ,  0.25],
       [ 0.25,  0.5 ,  0.  ,  0.25, -0.25,  0.5 ],
       [-0.5 ,  0.25, -0.25,  0.  , -0.5 , -0.25]])

### np.arange()- create sequence of no. but return an array

In [26]:
y=np.arange(10,20,3)
y

array([10, 13, 16, 19])

In [29]:
y=np.arange(2,20,2).reshape(3,3)
y

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [31]:
np.arange(50)


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

### np.linspace() – Creates evenly spaced numbers

*   Use Case : Smooth graph and imterpolation




In [37]:
y=np.linspace(1,10,4)
y

array([ 1.,  4.,  7., 10.])

### np.eye( : Identity matrix)

In [38]:
y=np.eye(5)
y

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### np.full()

* All elements same value



In [41]:
y=np.full(3,4)
y

array([4, 4, 4])

In [40]:
y=np.full((2,3),99)
y

array([[99, 99, 99],
       [99, 99, 99]])

Random Functions

*   np.random.rand() : Returns float values (0.0 to 1.0)
*   np.random.randint() : Returns integer values  - Between specified low and high (like range())



In [44]:
y=np.random.rand(10)
y

array([0.88581436, 0.29943483, 0.36013456, 0.57547736, 0.67322883,
       0.60572086, 0.55148734, 0.05239549, 0.51207572, 0.13876922])

In [50]:
y=np.random.rand(2,5)
y

array([[0.28026301, 0.22913611, 0.85430699, 0.41142897, 0.88426493],
       [0.09657044, 0.79944465, 0.15067599, 0.75798915, 0.22720079]])

In [53]:
y=np.random.randint(10)
y

6

In [56]:
y=np.random.randint(3,21,(2,5))
y

array([[17, 11, 14,  5,  4],
       [ 6,  5, 12,  6, 11]])

In [59]:
y=np.random.randint(5,10,2)
y

array([5, 8])