<a href="https://colab.research.google.com/github/gitbyjay25/Phase25/blob/main/Numpy/Numpy4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Reshaping , Resizing & flattening

In [2]:
import numpy as np

In [12]:
a=np.array([1,3,4,5,7,8])
a


array([1, 3, 4, 5, 7, 8])

In [14]:
b=a.reshape(2,3)
b

array([[1, 3, 4],
       [5, 7, 8]])

### ravel() vs flatten() → Convert to 1D

In [15]:
a=np.array([[4,5,6,7],[2,5,8,9],[7,5,3,9]])
a

array([[4, 5, 6, 7],
       [2, 5, 8, 9],
       [7, 5, 3, 9]])

In [17]:
b=a.ravel()
b

array([4, 5, 6, 7, 2, 5, 8, 9, 7, 5, 3, 9])

In [18]:
b.flatten()
b

array([4, 5, 6, 7, 2, 5, 8, 9, 7, 5, 3, 9])

### resize() → Resize and change data permanently
⚠️ Extra size → fills with 0:

In [20]:
a=np.array([1,2,3,4,8])
a.resize(2,3)
a

array([[1, 2, 3],
       [4, 8, 0]])

### transpose() → Flip matrix

In [22]:
a=np.array(
    [
        [10,25,4],
        [78,23,47],
        [3,5,7]
    ]
)
a

array([[10, 25,  4],
       [78, 23, 47],
       [ 3,  5,  7]])

In [24]:
a.transpose()


array([[10, 78,  3],
       [25, 23,  5],
       [ 4, 47,  7]])

In [25]:
a.T

array([[10, 78,  3],
       [25, 23,  5],
       [ 4, 47,  7]])

### ✅ 5. .reshape(-1, 1) → For ML Input
Why Needed in ML?
Machine Learning algorithms like Scikit-Learn expect:

2D input array for features (X)

Even if you have only 1 feature



In [27]:
a=np.array([1,2,3,4,8])
a

array([1, 2, 3, 4, 8])

In [29]:
from types import new_class
new_a=a.reshape(-1,1)
new_a

array([[1],
       [2],
       [3],
       [4],
       [8]])

In [30]:
a = np.array([[10, 20],
              [30, 40],
              [50, 60]])
a

array([[10, 20],
       [30, 40],
       [50, 60]])

In [31]:
print(a.reshape(-1,1))

[[10]
 [20]
 [30]
 [40]
 [50]
 [60]]


In [32]:
print(a.reshape(2,-1))

[[10 20 30]
 [40 50 60]]
